version: '3.8'

services:
    forume-api:
        container_name: api-prod
        restart: always
        build:
            context: ./forum/api
            dockerfile: Dockerfile
        volumes:
            - ./forum/api/db:/go/src/app/db
        ports:
            - 8081:8081

    forume-client:
        container_name: client-prod
        restart: always
        build:
            context: ./forum-react
            dockerfile: Dockerfile.prod
        volumes:
            - './forum-react:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - forume-api
